project_name: mev-boost
builds:
  # -
  #   id: mev-boost
  #   env: []
  #   goos:
  #     - linux
  #     - darwin
  #   goarch:
  #     - amd64
  #     - arm64
  -
    id: mev-boost-portable
    ldflags: -X github.com/flashbots/mev-boost/config.Version={{.Version}}
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
      - CGO_CFLAGS="-D__BLST_PORTABLE__"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
