name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install cross-compiler for linux/arm64 and windows
        run: sudo apt-get -y install gcc-aarch64-linux-gnu gcc-mingw-w64
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --config .goreleaser-linux_windows.yaml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: mev-boost-linux_windows
          path: dist/mev-boost*
  build-darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --config .goreleaser-darwin.yaml --rm-dist 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: mev-boost-darwin
          path: dist/mev-boost*
  release:
    needs: [build-linux-windows, build-darwin]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Make directories
        run: |
          mkdir -p ./dist/linux_windows
          mkdir -p ./dist/darwin
      - name: Download Linux and Windows binaries
        uses: actions/download-artifact@v3
        with:
          name: mev-boost-linux_windows
          path: ./dist/linux_windows
      - name: Download Darwin binaries
        uses: actions/download-artifact@v3
        with:
          name: mev-boost-darwin
          path: ./dist/darwin
      - name: Merge checksum file
        run: |
          cd ./dist
          cat ./darwin/mev-boost*checksums.txt >> checksums.txt
          cat ./linux_windows/mev-boost*checksums.txt >> checksums.txt
          rm ./darwin/mev-boost*checksums.txt
          rm ./linux_windows/mev-boost*checksums.txt
      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --config .goreleaser-release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
